# Generated by Django 5.1.2 on 2024-11-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_remove_producto_fechaingreso_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateTimeField(),
        ),
    ]
