# Generated by Django 5.1.2 on 2024-11-15 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=500)),
                ('nombre_categoria', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=500)),
                ('stock', models.IntegerField()),
                ('codigo', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pagina.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Modificacion',
            fields=[
                ('id_modificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_modificacion', models.DateField()),
                ('razon', models.CharField(max_length=500)),
                ('cantidad_anterior', models.IntegerField()),
                ('nueva_cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='pagina.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('detalle', models.CharField(max_length=1000)),
                ('fecha_ingreso', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='pagina.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('salida_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('detalle', models.CharField(max_length=1000)),
                ('fecha_salida', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='pagina.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('apellido', models.CharField(max_length=500)),
                ('correo', models.EmailField(max_length=500)),
                ('telefono', models.CharField(max_length=500)),
                ('direccion', models.CharField(max_length=500)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='pagina.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_ingresos', to='pagina.ingreso')),
                ('modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_modificaciones', to='pagina.modificacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='pagina.producto')),
                ('salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_salidas', to='pagina.salida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='pagina.usuario')),
            ],
        ),
    ]
